{ config, lib, ... }:
let
  inherit (lib.generators) toLua;

  hexToRgba = hex: alpha: "rgba(${hex}${alpha})";

  # Parse "OUTPUT, MODE, POSITION, SCALE" monitor strings into attrsets passed
  # to hl.monitor(...). Whitespace around commas tolerated.
  parseMonitor =
    s:
    let
      parts = map lib.strings.trim (lib.splitString "," s);
    in
    {
      output = builtins.elemAt parts 0;
      mode = builtins.elemAt parts 1;
      position = builtins.elemAt parts 2;
      # scale accepts string|number; keep as-is so "auto" passes through.
      scale = builtins.elemAt parts 3;
    };

  # Wallpaper selection (theme → first file).
  wallpapers = {
    "catppuccin-mocha" = [
      "beach.jpg"
      "clouds-2.png"
      "gentlemen-sunset.png"
      "clouds-3.png"
      "blue-landscape.png"
      "yohoho.jpg"
      "railroad-2.jpg"
      "trippy-purple.png"
      "wheat.png"
      "waves.png"
      "wallpaper-theme-converter-5.png"
    ];
    "tokyo-night" = [ "1-Pawel-Czerwinski-Abstract-Purple-Blue.jpg" ];
    "kanagawa" = [ "kanagawa-1.png" ];
    "everforest" = [ "1-everforest.jpg" ];
    "nord" = [ "nord-1.png" ];
    "gruvbox" = [ "gruvbox-1.jpg" ];
    "gruvbox-light" = [ "gruvbox-1.jpg" ];
  };
  selectedWallpaper = builtins.elemAt wallpapers.${config.hm.theme} 0;
  wallpaperPath = "${config.home.homeDirectory}/Pictures/Wallpapers/${selectedWallpaper}";

  generated = {
    hostname = config.hm.hostName;
    has_nvidia = config.hm.hasNvidia;
    monitors = map parseMonitor config.hm.monitors;
    quick_apps = config.hm.quickAppBindings;
    headless_outputs = config.hm.hyprland.headlessOutputs;
    emergency_restore = {
      enable = config.hm.hyprland.emergencyRestore.enable;
      key = config.hm.hyprland.emergencyRestore.key;
    };
    theme = {
      active_border = hexToRgba config.colorScheme.palette.base0D "aa";
      inactive_border = hexToRgba config.colorScheme.palette.base09 "aa";
      wallpaper_path = wallpaperPath;
    };
  };
in
lib.mkIf config.hm.hyprland.enable {
  # Written into ~/.config/hypr/generated.lua; consumed by main.lua via
  # `local gen = require("generated")`.
  xdg.configFile."hypr/generated.lua".text = ''
    -- Generated by Nix from hm.* options. DO NOT EDIT.
    return ${toLua { } generated}
  '';
}
