# Start windows and panes at 1, not 0
set -g renumber-windows on

# Custom split bindings (Prefix + | or -)
# -c "#{pane_current_path}" makes new panes open in the same directory as the current pane
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Easy pane navigation with Prefix + hjkl (Vim-like)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


# Pane resizing with Prefix + HJKL (repeatable with -r)
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Cycle through windows easily
bind -r N next-window
bind -r P previous-window

# Allow applications to access system clipboard.
set -g set-clipboard on # or "on"
set -g @yank_selection 'clipboard' # or 'primary' 'secondary' or 'clipboard'
set -g @yank_selection_mouse 'clipboard' # or 'clipboard' 'primary' or 'secondary'
